[common]
Version = "0.0.1"
LogDir = "./logs"
LogLevel = 0
Debug = true

[network]
IPType = 1
IPInner = "127.0.0.1"
IPOuter = "127.0.0.1"
Port = [7500, 30000]

[dbaccount]
Name = "account"
Addrs = ["127.0.0.1:6379"]
Password = ""
DBIndex = 0

[dbtoken]
Name = "token"
Addrs = ["127.0.0.1:6379"]
Password = ""
DBIndex = 0

[dbserver]
Name = "server"
Addrs = ["127.0.0.1:6379"]
Password = ""
DBIndex = 0

[dbmgr]
Name = "mgr"
Addrs = ["127.0.0.1:6379"]
Password = ""
DBIndex = 0
